name: Trigger Target Workflow

on:
  workflow_dispatch:
  # status:
  #   workflow_run:
  #     workflows:
  #       - Terraform
  #     types:
  #       - completed

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger manifests workflow
        run: |
          # Set the required variables
          repo_owner="tomek-skrond" 
          repo_name="recipe-app-manifests"  
          event_type="trigger-workflow" 
          service="recipe-app-manifests"
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"unit\": false, \"integration\": true}}"
